//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : flyweight
//  @ File Name : CharacterFactory.h
//  @ Date : 2017/12/27
//  @ Author : Owen-Li
//
//


#if !defined(_CHARACTERFACTORY_H)
#define _CHARACTERFACTORY_H

#include <vector>
#include <iostream>
#include "Character.h"

class CharacterFactory {
public:
	CharacterFactory();
	~CharacterFactory();
	Character* getCharacter(string character);
private:
	vector<Character*> m_characters;
};

#endif  //_CHARACTERFACTORY_H
