//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : flyweight
//  @ File Name : Character.h
//  @ Date : 2017/12/27
//  @ Author : Owen-Li
//
//


#if !defined(_CHARACTER_H)
#define _CHARACTER_H
#include <iostream>

using namespace std;

class Character {
public:
	virtual ~Character();
	virtual void display();
	virtual void setSize(int width, int height);
        virtual string getName(){
          return name;
        };
protected:
	string name;
	int _width;
	int _height;
	Character();
};

#endif  //_CHARACTER_H
