//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : flyweight
//  @ File Name : ConcreteCharacterB.h
//  @ Date : 2017/12/27
//  @ Author : Owen-Li
//
//


#if !defined(_CONCRETECHARACTERB_H)
#define _CONCRETECHARACTERB_H
#include "Character.h"

class ConcreteCharacterB: public Character {
public:
	ConcreteCharacterB();
	~ConcreteCharacterB();
        //void display();
        //void setSize(int width, int height);

};

#endif  //_CONCRETECHARACTERB_H
