//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : flyweight
//  @ File Name : ConcreteCharacterA.h
//  @ Date : 2017/12/27
//  @ Author : Owen-Li
//
//


#if !defined(_CONCRETECHARACTERA_H)
#define _CONCRETECHARACTERA_H

#include "Character.h"

class ConcreteCharacterA : public Character {
public:
	ConcreteCharacterA();
	~ConcreteCharacterA();
	//void display();
	//void setSize(int width, int height);
};

#endif  //_CONCRETECHARACTERA_H
