//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : ArcDecorator.h
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//


#if !defined(_ARCDECORATOR_H)
#define _ARCDECORATOR_H

#include "Decorator.h"
#include "TV.h"

class ArcDecorator : public Decorator {
public:
	ArcDecorator(TV* tv);
	~ArcDecorator();
	void Operation();
private:
	void ArcPlay();
};

#endif  //_ARCDECORATOR_H
