//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : Decorator.h
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//


#if !defined(_DECORATOR_H)
#define _DECORATOR_H

#include "TV.h"

class Decorator : public TV {
public:
	Decorator(TV* tv);
	~Decorator();
	void Operation();
protected:
	TV* _tv;
};

#endif  //_DECORATOR_H
