//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : HdmiDecorator.h
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//


#if !defined(_HDMIDECORATOR_H)
#define _HDMIDECORATOR_H

#include "Decorator.h"
#include "TV.h"

class HdmiDecorator : public Decorator {
public:
	HdmiDecorator(TV* tv);
	~HdmiDecorator();
	void Operation();
private:
	void HdmiPlay();
};

#endif  //_HDMIDECORATOR_H
