//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : TV.h
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//


#if !defined(_TV_H)
#define _TV_H


class TV {
public:
	~TV();
	virtual void Operation() = 0;
protected:
	TV();
};

#endif  //_TV_H
