//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : TVPlay.h
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//


#if !defined(_TVPLAY_H)
#define _TVPLAY_H

#include "TV.h"

class TVPlay : public TV {
public:
	TVPlay();
	~TVPlay();
	void Operation();
};

#endif  //_TVPLAY_H
