//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : objectadapter
//  @ File Name : Adapter.cpp
//  @ Date : 2017/12/14
//  @ Author : Owen.Li
//
//

#include <iostream>
#include "Adapter.h"

Adapter::Adapter(Adaptee* _adaptee) {
    adaptee = _adaptee;
}

Adapter::~Adapter() {

}

void Adapter::Request() {
    std::cout<<"Adapter Request"<<std::endl;
    adaptee->SpecificRequest();
}

