//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : objectadapter
//  @ File Name : Target.cpp
//  @ Date : 2017/12/14
//  @ Author : Owen.Li
//
//


#include "Target.h"

Target::Target() {

}

Target::~Target() {

}

