//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Chain
//  @ File Name : FootballPlayer.cpp
//  @ Date : 2018/1/4
//  @ Author : Owen-Li
//
//
#include <iostream>
#include <string>
#include "FootballPlayer.h"

FootballPlayer::FootballPlayer(string name) {
  this->name = name;
}

FootballPlayer::~FootballPlayer() {

}

void FootballPlayer::HandleRequest(string str){
  if(this->name == str){
    std::cout<<this->name<<": 办理事务"<<std::endl;
  }else if(mSuccessor != NULL){
    std::cout<<this->name<<": 这个不归我管，你去找"<<mSuccessor->getName()<<std::endl;
    mSuccessor->HandleRequest(str);
  }else{
    std::cout<<this->name<<": 办不了"<<std::endl;
  }

}

