//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Chain
//  @ File Name : Handler.cpp
//  @ Date : 2018/1/4
//  @ Author : Owen-Li
//
//
#include <iostream>
#include <string>
#include "Handler.h"

void Handler::HandleRequest(string str) {
    
}

Handler::~Handler() {
  if(mSuccessor != NULL){
    this->mSuccessor = NULL;
  }
}

void Handler::setSuccessor(Handler* successor) {
  this->mSuccessor = successor;
}

string Handler::getName() {
  return this->name;
}

Handler::Handler() {

}

