//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Memento
//  @ File Name : Memento.h
//  @ Date : 2018/1/1
//  @ Author : Owen-Li
//
//


#if !defined(_MEMENTO_H)
#define _MEMENTO_H

#include <string>

using namespace std;

class Memento {
private:
        friend class Originator;
	string _state;
	Memento(const string& state);
	~Memento();
	string getState();
	void setState(const string& state);
};

#endif  //_MEMENTO_H
