//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Visitor
//  @ File Name : ConcreateElement.cpp
//  @ Date : 2018/1/4
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "ConcreateElement.h"


ConcreateElement::ConcreateElement(){

}

ConcreateElement::~ConcreateElement() {

}

void ConcreateElement::Accept(Visitor* vis) {
   std::cout<<this->count<<std::endl;
   vis->VisitConcreateElement(this);
}

