//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Visitor
//  @ File Name : Element.cpp
//  @ Date : 2018/1/4
//  @ Author : Owen-Li
//
//


#include "Element.h"

Element::Element():count(100) {

}

Element::~Element() {

}

