//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Visitor
//  @ File Name : Visitor.cpp
//  @ Date : 2018/1/4
//  @ Author : Owen-Li
//
//


#include "Visitor.h"

Visitor::~Visitor() {

}

Visitor::Visitor() {

}

