//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Proxy
//  @ File Name : Person.h
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#if !defined(_PERSON_H)
#define _PERSON_H


class Person {
public:
	virtual ~Person()=0;
	virtual void Request() = 0;
protected:
	Person();
};

#endif  //_PERSON_H
