//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Proxy
//  @ File Name : Tom.h
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#if !defined(_TOM_H)
#define _TOM_H

#include "Person.h"

class Tom : public Person {
public:
	Tom();
	~Tom();
	void Request();
};

#endif  //_TOM_H
