//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : adapter
//  @ File Name : Adapter.cpp
//  @ Date : 2017/12/14
//  @ Author : Owen.Li
//
//
#include <iostream>
#include "Adapter.h"

Adapter::Adapter() {

}

Adapter::~Adapter() {

}

void Adapter::Request() {
    std::cout<<"Adapter Request"<<std::endl;
    this->SpecificRequest();
}

