//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : adapter
//  @ File Name : Adaptee.cpp
//  @ Date : 2017/12/14
//  @ Author : Owen.Li
//
//
#include <iostream>
#include "Adaptee.h"

Adaptee::Adaptee() {

}

Adaptee::~Adaptee() {

}

void Adaptee::SpecificRequest() {
    std::cout<<"Adaptee SpecificRequest"<<std::endl;
}

