//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : State
//  @ File Name : ConcreteStateB.h
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//


#if !defined(_CONCRETESTATEB_H)
#define _CONCRETESTATEB_H

#include "StateBase.h"

class ConcreteStateB : public StateBase {
public:
	ConcreteStateB();
	~ConcreteStateB();
	void handle(Context* context);
};

#endif  //_CONCRETESTATEB_H
