//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : State
//  @ File Name : ConcreteStateA.h
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//


#if !defined(_CONCRETESTATEA_H)
#define _CONCRETESTATEA_H

#include "StateBase.h"
#include "Context.h"

class ConcreteStateA : public StateBase {
public:
	ConcreteStateA();
	~ConcreteStateA();
	void handle(Context* context);
};

#endif  //_CONCRETESTATEA_H
