//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : State
//  @ File Name : StateBase.h
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//


#if !defined(_STATEBASE_H)
#define _STATEBASE_H

#include "Context.h"
//class Context;

class StateBase {
public:
	virtual  ~StateBase();
	virtual void handle(Context* context) = 0;
protected:
	StateBase();
};

#endif  //_STATE_H
