//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Template
//  @ File Name : LetvBand.h
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#if !defined(_LETVBAND_H)
#define _LETVBAND_H

#include "TvMaker.h"

class LetvBand : public TvMaker {
public:
	LetvBand();
	~LetvBand();
protected:
	//void boardMaker();
	void wifiMaker();
};

#endif  //_LETVBAND_H
