//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Template
//  @ File Name : PptvBand.h
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#if !defined(_PPTVBAND_H)
#define _PPTVBAND_H

#include "TvMaker.h"

class PptvBand : public TvMaker {
public:
	PptvBand();
	~PptvBand();
protected:
	void boardMaker();
	void wifiMaker();
};

#endif  //_PPTVBAND_H
