//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Template
//  @ File Name : TvMaker.h
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#if !defined(_TVMAKER_H)
#define _TVMAKER_H


class TvMaker {
public:
	TvMaker();
	virtual ~TvMaker();
	void makeFlow();

private:
	void panelMaker();

protected:
	virtual void boardMaker();
	virtual void wifiMaker() = 0;
};

#endif  //_TVMAKER_H
