//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Mediator
//  @ File Name : ListCtrl.h
//  @ Date : 2018/1/1
//  @ Author : 
//
//


#if !defined(_LISTCTRL_H)
#define _LISTCTRL_H

#include "UIWindow.h"

class ListCtrl : public UIWindow {
public:
	ListCtrl();
	~ListCtrl();
	void onListCtrlClick();
	void updateImage();
};

#endif  //_LISTCTRL_H
