//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Mediator
//  @ File Name : ListView.h
//  @ Date : 2018/1/1
//  @ Author : 
//
//


#if !defined(_LISTVIEW_H)
#define _LISTVIEW_H

#include "UIWindow.h"

class ListView : public UIWindow {
public:
	ListView();
	~ListView();
	void onListViewDoubleClick();
	void updateFolder();
	void selectFolder();
};

#endif  //_LISTVIEW_H
