//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Mediator
//  @ File Name : TextEdit.h
//  @ Date : 2018/1/1
//  @ Author : 
//
//


#if !defined(_TEXTEDIT_H)
#define _TEXTEDIT_H

#include "UIWindow.h"

class TextEdit : public UIWindow {
public:
	TextEdit();
	~TextEdit();
	void onChangeText();
};

#endif  //_TEXTEDIT_H
