//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Mediator
//  @ File Name : UIControl.h
//  @ Date : 2018/1/1
//  @ Author : 
//
//


#if !defined(_UICONTROL_H)
#define _UICONTROL_H

#include "TextEdit.h"
#include "ListCtrl.h"
#include "ListView.h"

class UIControl {
public:
	UIControl();
	~UIControl();
	void setTextEdit(TextEdit* textedit);
	void setListCtrl(ListCtrl* listctrl);
	void setListView(ListView* listview);
	void onChangeText();
	void onListCtrlClick();
	void onListViewDoubleClick();
private:
	TextEdit* mTextEdit;
	ListCtrl* mListCtrl;
	ListView* mListView;
};

#endif  //_UICONTROL_H
