//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Mediator
//  @ File Name : UIWindow.h
//  @ Date : 2018/1/1
//  @ Author : 
//
//


#if !defined(_UIWINDOW_H)
#define _UIWINDOW_H

class UIControl;

class UIWindow {
public:
        virtual ~UIWindow();
	void setUIControl(UIControl* uicontrol);
	UIControl* getUIControl();
protected:
	UIWindow();
private:
	UIControl* mUIControl;
};

#endif  //_UIWINDOW_H
