//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : Abstraction.h
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//


#if !defined(_ABSTRACTION_H)
#define _ABSTRACTION_H


class Abstraction {
public:
    virtual void Operation1() = 0;

protected:
    Abstraction();
};

#endif  //_ABSTRACTION_H
