//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : AbstractionImplement.h
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//


#if !defined(_ABSTRACTIONIMPLEMENT_H)
#define _ABSTRACTIONIMPLEMENT_H


class AbstractionImplement {
public:
    virtual void Operation1() = 0;
protected:
    AbstractionImplement();
};

#endif  //_ABSTRACTIONIMPLEMENT_H
