//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : ConcreatAbstractionImplementA.h
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//


#if !defined(_CONCREATABSTRACTIONIMPLEMENTA_H)
#define _CONCREATABSTRACTIONIMPLEMENTA_H

#include "AbstractionImplement.h"

class ConcreatAbstractionImplementA : public AbstractionImplement {
public:
    ConcreatAbstractionImplementA();
    void Operation1();
};

#endif  //_CONCREATABSTRACTIONIMPLEMENTA_H
