//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : ConcreatAbstractionImplementB.h
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//


#if !defined(_CONCREATABSTRACTIONIMPLEMENTB_H)
#define _CONCREATABSTRACTIONIMPLEMENTB_H

#include "AbstractionImplement.h"

class ConcreatAbstractionImplementB : public AbstractionImplement {
public:
    ConcreatAbstractionImplementB();
    void Operation1();
};

#endif  //_CONCREATABSTRACTIONIMPLEMENTB_H
