//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : RefinedAbstractionB.h
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//


#if !defined(_REFINEDABSTRACTIONB_H)
#define _REFINEDABSTRACTIONB_H

#include "Abstraction.h"
#include "AbstractionImplement.h"

class RefinedAbstractionB : public Abstraction {
public:
    RefinedAbstractionB(AbstractionImplement& impl);
    void Operation1();

private:
    AbstractionImplement* _impl;
};

#endif  //_REFINEDABSTRACTIONB_H
