//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Strategy
//  @ File Name : AK47.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "AK47.h"

AK47::AK47() {

}

AK47::~AK47() {

}

void AK47::open() {
  std::cout<<"AK47 open"<<std::endl;
}

void AK47::fire() {
  std::cout<<"AK47 fire"<<std::endl;
}

void AK47::close() {
  std::cout<<"AK47 close"<<std::endl;
}

