//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Strategy
//  @ File Name : Context.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#include "Context.h"

Context::Context() {

}

Context::~Context() {

}

void Context::setWeapon(Weapon* weapon) {
  this->_weapon = weapon;
}

void Context::kill() {
  this->_weapon->useWeapon();
}

