//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Strategy
//  @ File Name : M16.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "M16.h"

M16::M16() {

}

M16::~M16() {

}

void M16::open() {
  std::cout<<"M16 open"<<std::endl;
}

void M16::fire() {
  std::cout<<"M16 fire"<<std::endl;
}

void M16::close() {
  std::cout<<"M16 close"<<std::endl;
}

