//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Strategy
//  @ File Name : Weapon.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#include "Weapon.h"

void Weapon::useWeapon() {
  this->open();
  this->fire();
  this->close();
}

Weapon::Weapon() {

}

Weapon::~Weapon() {

}
