//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Arc.cpp
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//


#include "Arc.h"
#include <iostream>

Arc::Arc() {

}

Arc::~Arc() {

}

void Arc::Operation1() {
  std::cout<<"arc function"<<std::endl;
}

