//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Atv.cpp
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//


#include "Atv.h"
#include <iostream>

Atv::Atv() {

}

Atv::~Atv() {

}

void Atv::Operation1() {
  std::cout<<"atv function"<<std::endl;
}

