//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Cec.cpp
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "Cec.h"

Cec::Cec() {

}

Cec::~Cec() {

}

void Cec::Operation1() {
  std::cout<<"CEC function"<<std::endl;
}

