//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Dtv.cpp
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "Dtv.h"

Dtv::Dtv() {

}

Dtv::~Dtv() {

}

void Dtv::Operation1() {
   std::cout<<"DTV function"<<std::endl;
}

