//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Facade.cpp
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "Facade.h"
#include "Atv.h"
#include "Dtv.h"
#include "Cec.h"
#include "Arc.h"
#include "Launcher.h"
#include "Player.h"

Facade::Facade() {

}

Facade::~Facade() {

}

void Facade::tv() {
  std::cout<<"Facade->TV function"<<std::endl;
  Atv atv;
  Dtv dtv;
  Player player;

  atv.Operation1();
  dtv.Operation1();
  player.Operation1();
}

void Facade::onlineplay() {
  std::cout<<"Facade->ONLINEPLAY function"<<std::endl;
  Launcher launcher;
  Player player;

  launcher.Operation1();
  player.Operation1();
}

void Facade::sourcein() {
  std::cout<<"Facade->SOURCEIN function"<<std::endl;
  Cec cec;
  Arc arc;
  Player player;

  cec.Operation1();
  arc.Operation1();
  player.Operation1();
}

