//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : launcher.cpp
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "Launcher.h"

Launcher::Launcher() {

}

Launcher::~Launcher() {

}

void Launcher::Operation1() {
  std::cout<<"Launcher function"<<std::endl;
}

