//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Player.cpp
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "Player.h"

Player::Player() {

}

Player::~Player() {

}

void Player::Operation1() {
   std::cout<<"Player function"<<std::endl;
}

