//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Memento
//  @ File Name : Originator.cpp
//  @ Date : 2018/1/1
//  @ Author : Owen-Li
//
//

#include <string>
#include "Originator.h"
#include "Memento.h"

using namespace std;

Originator::Originator(const string &state) {
  this->_state = state;
} 

Originator::~Originator() {

}

void Originator::restoreFromMemento(Memento* m) {
  this->_state = m->getState();
}

Memento* Originator::createMemento() {
  return new Memento(_state);
}

void Originator::setState(const string & state) {
  this->_state = state;
}

string Originator::getState() {
  return this->_state;
}

void Originator::destroyMemento(Memento* memento){
  if(memento){
    delete memento;
    memento = NULL;
  }
}
