//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Mediator
//  @ File Name : ListView.cpp
//  @ Date : 2018/1/1
//  @ Author : 
//
//

#include <iostream>
#include "UIControl.h"
#include "ListView.h"

ListView::ListView() {

}

ListView::~ListView() {

}

void ListView::onListViewDoubleClick() {
  UIControl* pUIControl = getUIControl();
  if(pUIControl){
    pUIControl->onListViewDoubleClick();
  }
}

void ListView::updateFolder() {
  std::cout<<"ListView is updating folder..."<<std::endl;
}

void ListView::selectFolder() {
  std::cout<<"ListView is selecting folder..."<<std::endl;
}

