//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Mediator
//  @ File Name : UIControl.cpp
//  @ Date : 2018/1/1
//  @ Author : 
//
//

#include <iostream>
#include "TextEdit.h"
#include "ListCtrl.h"
#include "ListView.h"
#include "UIControl.h"

UIControl::UIControl() {
  this->mTextEdit = NULL;
  this->mListView = NULL;
  this->mListCtrl = NULL;
}

UIControl::~UIControl() {

}

void UIControl::setTextEdit(TextEdit* textedit) {
  if(textedit){
    this->mTextEdit = textedit;
  }
}

void UIControl::setListCtrl(ListCtrl* listctrl) {
  if(listctrl){
    this->mListCtrl = listctrl;
  }
}

void UIControl::setListView(ListView* listview) {
  if(listview){
    this->mListView = listview;
  }
}

void UIControl::onChangeText() {
  if(this->mListView){
    this->mListView->updateFolder();
  }
  if(this->mListCtrl){
    this->mListCtrl->updateImage();
  }
}

void UIControl::onListCtrlClick() {
  if(this->mListView){
    this->mListView->selectFolder();
  }
}

void UIControl::onListViewDoubleClick() {
  if(this->mListCtrl){
    this->mListCtrl->updateImage();
  }
}

