//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Mediator
//  @ File Name : UIWindow.cpp
//  @ Date : 2018/1/1
//  @ Author : 
//
//


#include "UIWindow.h"

UIWindow::~UIWindow() {

}

void UIWindow::setUIControl(UIControl* uicontrol) {
  this->mUIControl = uicontrol;
}

UIControl* UIWindow::getUIControl() {
  return this->mUIControl;
}

UIWindow::UIWindow() {

}

