//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Prototype
//  @ File Name : ConcretePrototype2.cpp
//  @ Date : 2017/12/6
//  @ Author : owen.li
//
//
#include <iostream>
#include "ConcretePrototype2.h"
#include "Prototype.h"

ConcretePrototype2::ConcretePrototype2(){
   std::cout<<"construct ConcretePrototype2"<<std::endl;
}

ConcretePrototype2::ConcretePrototype2(const ConcretePrototype2& p2){
   std::cout<<"copy construct ConcretePrototype2"<<std::endl;
}

Prototype* ConcretePrototype2::Clone() {
  return new ConcretePrototype2(*this);
}

