//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : adapter
//  @ File Name : Adapter.h
//  @ Date : 2017/12/14
//  @ Author : Owen.Li
//
//


#if !defined(_ADAPTER_H)
#define _ADAPTER_H

#include "Target.h"
#include "Adaptee.h"

class Adapter : public Target, private Adaptee {
public:
	Adapter();
	~Adapter();
	void Request();
};

#endif  //_ADAPTER_H
