//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : adapter
//  @ File Name : Target.h
//  @ Date : 2017/12/14
//  @ Author : Owen.Li
//
//


#if !defined(_TARGET_H)
#define _TARGET_H


class Target {
public:
	Target();
	~Target();
	virtual void Request() = 0;
};

#endif  //_TARGET_H
