//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : composite
//  @ File Name : Composite.h
//  @ Date : 2017/12/25
//  @ Author : Owen-Li
//
//


#if !defined(_COMPOSITE_H)
#define _COMPOSITE_H

#include "Component.h"
#include <string>
#include <vector>


class Composite : public Component {
public:
	vector<Component *> m_vecComp;

	Composite(string compname);
	~Composite();
	void Operation();
	void Add(Component* component);
	void Remove(Component* component);
	Component* GetChild(int index);
	void Print();
};

#endif  //_COMPOSITE_H
