//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : composite
//  @ File Name : Component.h
//  @ Date : 2017/12/25
//  @ Author : Owen-Li
//
//


#if !defined(_COMPONENT_H)
#define _COMPONENT_H

#include <string>
using namespace std;
class Component {
public:
	Component(string compname);
        virtual	~Component();
	virtual void Operation() = 0;
	virtual void Add(Component* component) = 0;
	virtual void Remove(Component* component) = 0;
	virtual Component* GetChild(int index) = 0;
	virtual void Print() = 0;
	string getName();

protected:
	string compName;
};

#endif  //_COMPONENT_H
