//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : objectadapter
//  @ File Name : Adapter.h
//  @ Date : 2017/12/14
//  @ Author : Owen.Li
//
//


#if !defined(_ADAPTER_H)
#define _ADAPTER_H

#include "Target.h"
#include "Adaptee.h"

class Adapter : public Target{
public:
	Adapter(Adaptee* _adaptee);
	~Adapter();
	void Request();
private:
	Adaptee* adaptee;
};

#endif  //_ADAPTER_H
