//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : objectadapter
//  @ File Name : Adaptee.h
//  @ Date : 2017/12/14
//  @ Author : Owen.Li
//
//


#if !defined(_ADAPTEE_H)
#define _ADAPTEE_H


class Adaptee {
public:
	Adaptee();
	~Adaptee();
	void SpecificRequest();
};

#endif  //_ADAPTEE_H
