//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Proxy
//  @ File Name : Person.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#include "Person.h"

Person::Person() {

}
Person::~Person() {

}
