//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Proxy
//  @ File Name : ProxyTom.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "ProxyTom.h"

ProxyTom::ProxyTom() {

}

ProxyTom::~ProxyTom() {

}

void ProxyTom::Request() {
  std::cout<<"I am Proxy of Tom, Tom say: "<<std::endl;
  if(tom == NULL){
    tom = new Tom();
  }

  tom->Request();
}

