//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Proxy
//  @ File Name : Tom.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "Tom.h"

Tom::Tom() {

}

Tom::~Tom() {

}

void Tom::Request() {
  std::cout<<"I Love You!!!"<<std::endl;
}

