//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : ArcDecorator.cpp
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//

#include "iostream"
#include "ArcDecorator.h"

ArcDecorator::ArcDecorator(TV* tv) : Decorator(tv) {

}

ArcDecorator::~ArcDecorator() {

}

void ArcDecorator::Operation() {
  this->_tv->Operation();
  ArcPlay();
}

void ArcDecorator::ArcPlay() {
  std::cout<<"ArcDecorator ArcPlay"<<std::endl;
}

