//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : CecDecorator.cpp
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//

#include <iostream>
#include "CecDecorator.h"

CecDecorator::CecDecorator(TV* tv) : Decorator(tv){

}

CecDecorator::~CecDecorator() {

}

void CecDecorator::Operation() {
  _tv->Operation();
  CecPlay();
}

void CecDecorator::CecPlay() {
  std::cout<<"CecDecorator CecPlay"<<std::endl;
}

