//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : Decorator.cpp
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//
#include "iostream"
#include "Decorator.h"

Decorator::Decorator(TV* tv) {
  _tv = tv;
}

Decorator::~Decorator() {
  _tv = NULL;  
}

void Decorator::Operation() {
}

