//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : HdmiDecorator.cpp
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//

#include <iostream>
#include "HdmiDecorator.h"

HdmiDecorator::HdmiDecorator(TV* tv) : Decorator(tv){
  
}

HdmiDecorator::~HdmiDecorator() {

}

void HdmiDecorator::Operation() {
  _tv->Operation();
  HdmiPlay();
}

void HdmiDecorator::HdmiPlay() {
  std::cout<<"HdmiDecorator HdmiPlay"<<std::endl;
}

