//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : TV.cpp
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//


#include "TV.h"

TV::~TV() {

}

TV::TV() {

}

