//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : decorator
//  @ File Name : TVPlay.cpp
//  @ Date : 2017/12/15
//  @ Author : Owen.Li
//
//

#include <iostream>
#include "TVPlay.h"

TVPlay::TVPlay() {

}

TVPlay::~TVPlay() {

}

void TVPlay::Operation() {
  std::cout<<"TVPlay Operation"<<std::endl;
}

