//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Observer
//  @ File Name : Observer.h
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//


#if !defined(_OBSERVER_H)
#define _OBSERVER_H

#include <string>


class Observer {
public:
        virtual	~Observer();
	virtual void update(const std::string &msg) = 0;
protected:
	Observer();
};

#endif  //_OBSERVER_H
