//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Observer
//  @ File Name : WeiXin.h
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//


#if !defined(_WEIXIN_H)
#define _WEIXIN_H
#include <string>
#include "Subject.h"

class WeiXin : public Subject {
public:
	~WeiXin();
	WeiXin();
};

#endif  //_WEIXIN_H
