//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Iteratro
//  @ File Name : Iterator.h
//  @ Date : 2018/1/10
//  @ Author : Owen-Li
//
//


#if !defined(_ITERATOR_H)
#define _ITERATOR_H

template<class Item>
class Iterator {
public:
	virtual ~Iterator();
	virtual void First() = 0;
	virtual void Next() = 0;
	virtual bool IsDone() = 0;
	virtual Item* CurrentItem() = 0;
protected:
	Iterator();
};

template<class Item>
Iterator<Item>::~Iterator() {

}

template<class Item>
Iterator<Item>::Iterator() {

}

#endif  //_ITERATOR_H
