//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Arc.h
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//


#if !defined(_ARC_H)
#define _ARC_H


class Arc {
public:
	Arc();
	~Arc();
	void Operation1();
};

#endif  //_ARC_H
