//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Atv.h
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//


#if !defined(_ATV_H)
#define _ATV_H


class Atv {
public:
	Atv();
	~Atv();
	void Operation1();
};

#endif  //_ATV_H
