//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Cec.h
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//


#if !defined(_CEC_H)
#define _CEC_H


class Cec {
public:
	Cec();
	~Cec();
	void Operation1();
};

#endif  //_CEC_H
