//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Dtv.h
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//


#if !defined(_DTV_H)
#define _DTV_H


class Dtv {
public:
	Dtv();
	~Dtv();
	void Operation1();
};

#endif  //_DTV_H
