//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Facade.h
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//


#if !defined(_FACADE_H)
#define _FACADE_H


class Facade {
public:
	Facade();
	~Facade();
	void tv();
	void onlineplay();
	void sourcein();
};

#endif  //_FACADE_H
