//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : launcher.h
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//


#if !defined(_LAUNCHER_H)
#define _LAUNCHER_H


class Launcher {
public:
	Launcher();
	~Launcher();
	void Operation1();
};

#endif  //_LAUNCHER_H
