//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : facade
//  @ File Name : Player.h
//  @ Date : 2017/12/26
//  @ Author : Owen-Li
//
//


#if !defined(_PLAYER_H)
#define _PLAYER_H


class Player {
public:
	Player();
	~Player();
	void Operation1();
};

#endif  //_PLAYER_H
