//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : flyweight
//  @ File Name : CharacterFactory.cpp
//  @ Date : 2017/12/27
//  @ Author : Owen-Li
//
//

#include <iostream>
#include <vector>
#include <string>
#include "CharacterFactory.h"
#include "Character.h"
#include "ConcreteCharacterA.h"
#include "ConcreteCharacterB.h"

CharacterFactory::CharacterFactory() {

}

CharacterFactory::~CharacterFactory() {

}

Character* CharacterFactory::getCharacter(string character) {
  vector<Character*>::iterator  it = m_characters.begin();

  for (; it != m_characters.end(); ++it){
    if((*it)->getName() == character){
      std::cout<<"Found Character object "<<character<<std::endl;
      return *it;
    }
  }
  
  std::cout<<"Create new Character object "<<character<<std::endl;
  Character* cha = NULL;
  if(character == "A"){
    cha = new ConcreteCharacterA();
  }else if(character == "B"){
    cha = new ConcreteCharacterB();
  }else{
    cha = NULL;
  }

  
  m_characters.push_back(cha);
 return cha;
}

