//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : flyweight
//  @ File Name : ConcreteCharacterB.cpp
//  @ Date : 2017/12/27
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "ConcreteCharacterB.h"

ConcreteCharacterB::ConcreteCharacterB() {
  this->name = "B";
  this->_width = 100;
  this->_height = 100;
}

ConcreteCharacterB::~ConcreteCharacterB() {

}
/*
void ConcreteCharacterB::display() {
  std::cout<<"Character "<<this->name<<",width = "<<this->_width<<",height = "<< this->_height<<std::endl;
}

void ConcreteCharacterB::setSize(int width, int height) {
  this->_width = width;
  this->_height = height;
}
*/
