//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : flyweight
//  @ File Name : ConcreteCharacterA.cpp
//  @ Date : 2017/12/27
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "ConcreteCharacterA.h"

ConcreteCharacterA::ConcreteCharacterA() {
  this->name = "A";
  this->_width = 100;
  this->_height = 100;
}

ConcreteCharacterA::~ConcreteCharacterA() {
  
}
/*
void ConcreteCharacterA::display() {
  //std::cout<<"Character "<<this->name<<",width = "<<this->_width<<",height = "<< this->_height<<std::endl;
}

void ConcreteCharacterA::setSize(int width, int height) {
  //this->_width = width;
  //this->_height = height;
}
*/
