//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Visitor
//  @ File Name : ConcreteVisitor.h
//  @ Date : 2018/1/4
//  @ Author : Owen-Li
//
//


#if !defined(_CONCRETEVISITOR_H)
#define _CONCRETEVISITOR_H

#include "Visitor.h"


class ConcreteVisitor : public Visitor {
public:
	ConcreteVisitor();
	~ConcreteVisitor();
	void VisitConcreateElement(Element* elem);
};

#endif  //_CONCRETEVISITOR_H
