//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Visitor
//  @ File Name : Element.h
//  @ Date : 2018/1/4
//  @ Author : Owen-Li
//
//


#if !defined(_ELEMENT_H)
#define _ELEMENT_H

#include "Visitor.h"
//class Visitor;

class Element {
public:	
	int count;
public:
	virtual ~Element();
	virtual void Accept(Visitor* v) = 0;
protected:
	Element();
};

#endif  //_ELEMENT_H
