//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Visitor
//  @ File Name : Visitor.h
//  @ Date : 2018/1/4
//  @ Author : Owen-Li
//
//


#if !defined(_VISITOR_H)
#define _VISITOR_H

//#include "Element.h"
class Element;

class Visitor {
public:
	virtual ~Visitor();
	virtual void VisitConcreateElement(Element* elem) = 0;
protected:
	Visitor();
};

#endif  //_VISITOR_H
