//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Prototype
//  @ File Name : ConcretePrototype2.h
//  @ Date : 2017/12/6
//  @ Author : owen.li
//
//


#if !defined(_CONCRETEPROTOTYPE2_H)
#define _CONCRETEPROTOTYPE2_H

#include "Prototype.h"

class ConcretePrototype2 : public Prototype {
public:
    ConcretePrototype2();
    ConcretePrototype2(const ConcretePrototype2&);
    ~ConcretePrototype2();
    Prototype* Clone();
};

#endif  //_CONCRETEPROTOTYPE2_H
