//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Prototype
//  @ File Name : ConcretePrototype1.h
//  @ Date : 2017/12/6
//  @ Author : owen.li
//
//


#if !defined(_CONCRETEPROTOTYPE1_H)
#define _CONCRETEPROTOTYPE1_H

#include "Prototype.h"

class ConcretePrototype1 : public Prototype {
public:
    ConcretePrototype1();
    ConcretePrototype1(const ConcretePrototype1&);
    ~ConcretePrototype1();
    virtual Prototype* Clone();
};

#endif  //_CONCRETEPROTOTYPE1_H
