//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Prototype
//  @ File Name : Prototype.h
//  @ Date : 2017/12/6
//  @ Author : owen.li
//
//


#if !defined(_PROTOTYPE_H)
#define _PROTOTYPE_H


class Prototype {
public:
    Prototype(){};
    ~Prototype(){};
    virtual Prototype* Clone() = 0;
};

#endif  //_PROTOTYPE_H
