//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Command
//  @ File Name : Command.h
//  @ Date : 2018/1/3
//  @ Author : Owen-Li
//
//


#if !defined(_COMMAND_H)
#define _COMMAND_H


class Command {
public:
	virtual ~Command();
	virtual void Execute() = 0;
protected:
	Command();
};

#endif  //_COMMAND_H
