//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Command
//  @ File Name : ConcreteCommand.h
//  @ Date : 2018/1/3
//  @ Author : Owen-Li
//
//


#if !defined(_CONCRETECOMMAND_H)
#define _CONCRETECOMMAND_H

#include "Command.h"
#include "Receiver.h"

class ConcreteCommand : public Command {
public:
	ConcreteCommand(Receiver* receiver);
	~ConcreteCommand();
	void Execute();

private:
   	Receiver* mReceiver;
};

#endif  //_CONCRETECOMMAND_H
