//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Command
//  @ File Name : Invoker.h
//  @ Date : 2018/1/3
//  @ Author : Owen-Li
//
//


#if !defined(_INVOKER_H)
#define _INVOKER_H

#include "Command.h"

class Invoker {
public:
	Invoker(Command* command);
	~Invoker();
	void invoke();
private:
	Command* mCommand;
};

#endif  //_INVOKER_H
