//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Command
//  @ File Name : Receiver.h
//  @ Date : 2018/1/3
//  @ Author : Owen-Li
//
//


#if !defined(_RECEIVER_H)
#define _RECEIVER_H


class Receiver {
public:
	void Action();
	Receiver();
	~Receiver();
};

#endif  //_RECEIVER_H
