//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Observer
//  @ File Name : Observer.cpp
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//


#include "Observer.h"

Observer::~Observer() {

}

Observer::Observer() {

}

