//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Observer
//  @ File Name : RoomMate.cpp
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//

#include <iostream>
#include <string>
#include "RoomMate.h"

using namespace std;

RoomMate::RoomMate(string name, string now, string next):_name(name),_now(now),_next(next){}

RoomMate::~RoomMate() {
  _name = "";
  _now = "";
  _next = "";
}

void RoomMate::update(const string &msg) {
  cout<<"This is "<<this->_name<<endl;
  if(msg == "meidianming"){
    cout<<"Now : "<<this->_now<<endl;
  }else if(msg == "dianming"){
    cout<<"Next : "<<this->_next<<endl;
  }else{
    cout<<"unknown msg, do nothing"<<endl;
  }  
}

