//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Observer
//  @ File Name : WeiXin.cpp
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//

#include <iostream>
#include <string>
#include "WeiXin.h"

using namespace std;

WeiXin::~WeiXin() {

}

WeiXin::WeiXin() {

}

