//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Strategy
//  @ File Name : AK47.h
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#if !defined(_AK47_H)
#define _AK47_H

#include "Weapon.h"

class AK47 : public Weapon {
public:
	AK47();
	~AK47();
	void open();
	void fire();
	void close();
};

#endif  //_AK47_H
