//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Strategy
//  @ File Name : M16.h
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//


#if !defined(_M16_H)
#define _M16_H

#include "Weapon.h"

class M16 : public Weapon {
public:
	M16();
	~M16();
	void open();
	void fire();
	void close();
};

#endif  //_M16_H
