//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Command
//  @ File Name : ConcreteCommand.cpp
//  @ Date : 2018/1/3
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "ConcreteCommand.h"

ConcreteCommand::ConcreteCommand(Receiver* receiver): mReceiver(receiver) {
 
}

ConcreteCommand::~ConcreteCommand() {
     this->mReceiver = NULL;
}

void ConcreteCommand::Execute() {
  this->mReceiver->Action();
}

