//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Command
//  @ File Name : Invoker.cpp
//  @ Date : 2018/1/3
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "Invoker.h"

Invoker::Invoker(Command* command): mCommand(command) {

}

Invoker::~Invoker() {
  this->mCommand = NULL;
}
 
void Invoker::invoke() {
  this->mCommand->Execute();
}

