//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Command
//  @ File Name : Receiver.cpp
//  @ Date : 2018/1/3
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "Receiver.h"

void Receiver::Action() {
  std::cout<<"Receiver Action......"<<std::endl;
}

Receiver::Receiver() {

}

Receiver::~Receiver() {

}

