//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Chain
//  @ File Name : FootballPlayer.h
//  @ Date : 2018/1/4
//  @ Author : Owen-Li
//
//


#if !defined(_FOOTBALLPLAYER_H)
#define _FOOTBALLPLAYER_H
#include <string>
#include "Handler.h"

class FootballPlayer : public Handler {
public:
	FootballPlayer(string name);
	~FootballPlayer();
	void HandleRequest(string str);
};

#endif  //_FOOTBALLPLAYER_H
