//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : composite
//  @ File Name : Component.cpp
//  @ Date : 2017/12/25
//  @ Author : Owen-Li
//
//


#include "Component.h"
#include <string>
#include <iostream>

Component::Component(string compname): compName(compname) {
  
}

Component::~Component() {
  std::cout<<":~Component"<<std::endl;
}

string Component::getName() {
  return compName;
}

