//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : composite
//  @ File Name : Leaf.cpp
//  @ Date : 2017/12/25
//  @ Author : Owen-Li
//
//

#include <iostream>
#include <string>
#include "Leaf.h"

Leaf::Leaf(string compname): Component(compname) {

}

Leaf::~Leaf() {

}

void Leaf::Operation() {
  std::cout<<"I am "<<compName<<std::endl;
}

void Leaf::Add(Component* component) {

}

void Leaf::Remove(Component* component) {

}

Component* Leaf::GetChild(int index) {
  return NULL;
}

void Leaf::Print() {
  
}

