//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : AbstractionImplement.cpp
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//


#include "AbstractionImplement.h"

AbstractionImplement::AbstractionImplement() {

}

