//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : Abstraction.cpp
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//


#include "Abstraction.h"

Abstraction::Abstraction() {

}

