//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : ConcreatAbstractionImplementA.cpp
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//

#include <iostream>
#include "ConcreatAbstractionImplementA.h"

using namespace std;

ConcreatAbstractionImplementA::ConcreatAbstractionImplementA() {

}

void ConcreatAbstractionImplementA::Operation1() {
    cout<<"ConcreatAbstractionImplementA Operation1" <<endl;
}


