//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : ConcreatAbstractionImplementB.cpp
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//

#include <iostream>
#include "ConcreatAbstractionImplementB.h"

using namespace std;

ConcreatAbstractionImplementB::ConcreatAbstractionImplementB() {

}

void ConcreatAbstractionImplementB::Operation1() {
    cout<<"ConcreatAbstractionImplementB Operation1" <<endl;
}

