//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : RefinedAbstractionB.cpp
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//

#include<iostream>
#include "RefinedAbstractionB.h"

using namespace std;

RefinedAbstractionB::RefinedAbstractionB(AbstractionImplement& impl) {
    this->_impl = &impl;
}

void RefinedAbstractionB::Operation1() {
    cout<<"RefinedAbstractionB Operation1"<<endl;
    _impl->Operation1();
}


