//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Bridge
//  @ File Name : RefinedAbstractionA.cpp
//  @ Date : 2017/12/8
//  @ Author : owen.li
//
//

#include<iostream>
#include "RefinedAbstraction.h"

using namespace std;

RefinedAbstraction::RefinedAbstraction(AbstractionImplement& impl) {
    this->_impl = &impl;
}

void RefinedAbstraction::Operation1() {
    cout<<"RefinedAbstractionA Operation1"<<endl;
    _impl->Operation1();
}


