//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : State
//  @ File Name : ConcreteStateA.cpp
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "ConcreteStateA.h"
#include "Context.h"

ConcreteStateA::ConcreteStateA() {

}

ConcreteStateA::~ConcreteStateA() {

}

void ConcreteStateA::handle(Context* context) {
  std::cout<<"I am on ConcreteStateA, handling......"<<std::endl;
}

