//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : State
//  @ File Name : ConcreteStateB.cpp
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "ConcreteStateB.h"
#include "Context.h"

ConcreteStateB::ConcreteStateB() {

}

ConcreteStateB::~ConcreteStateB() {

}

void ConcreteStateB::handle(Context* context) {
  std::cout<<"I am on ConcreteStateB, handling......"<<std::endl;
}

