//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : State
//  @ File Name : Context.cpp
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "Context.h"
#include "StateBase.h"

Context::Context(StateBase* state): _state(state) {

}

Context::~Context() {
  _state = NULL;
}

void Context::request() {
  if(_state != NULL){
    _state->handle(this);
  }
}

void Context::changeState(StateBase* state){
  _state = state;
}
