//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : State
//  @ File Name : State.cpp
//  @ Date : 2017/12/29
//  @ Author : Owen-Li
//
//


#include "StateBase.h"

StateBase::~StateBase() {

}

StateBase::StateBase() {

}

