//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Template
//  @ File Name : LetvBand.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "LetvBand.h"

LetvBand::LetvBand() {

}

LetvBand::~LetvBand() {

}

void LetvBand::wifiMaker() {
  std::cout<<"Use Broadcom wifi"<<std::endl;
}

