//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Template
//  @ File Name : PptvBand.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "PptvBand.h"

PptvBand::PptvBand() {

}

PptvBand::~PptvBand() {

}

void PptvBand::boardMaker() {
  std::cout<<"Use CVTE board"<<std::endl;
}

void PptvBand::wifiMaker() {
  std::cout<<"Use Realtek wifi"<<std::endl;
}

