//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Template
//  @ File Name : TvMaker.cpp
//  @ Date : 2017/12/28
//  @ Author : Owen-Li
//
//

#include <iostream>
#include "TvMaker.h"

TvMaker::TvMaker() {

}

TvMaker::~TvMaker() {

}

void TvMaker::makeFlow() {
  std::cout<<"Start design TV"<<std::endl;
  this->panelMaker();
  this->boardMaker();
  this->wifiMaker();
  std::cout<<"Design TV successfully!"<<std::endl;
}

void TvMaker::panelMaker() {
  std::cout<<"Use default LG panel"<<std::endl;
}

void TvMaker::boardMaker() {
  std::cout<<"Use default CTV board"<<std::endl;
}
